### ISSUE TITLE
Docker 環境配置遇到的問題

### ISSUE THREAD

**Issue by yue0211** [kuwaai/genai-os#13]
使用Docker配置完環境後，container: kuwa-web-1 無法正確運行，log 內容為 : nginx: [emerg] host not found in upstream "multi-chat" in /etc/nginx/conf.d/default.conf:26。

想問該如何修正這個問題?

**Comment by ifTNT** [comment]
您好，請問container kuwa-multi-chat-1有成功跑起來嗎? 有沒有任何錯誤訊息?

**Comment by yue0211** [comment]
![image](https://github.com/kuwaai/genai-os/assets/82385589/d0687bc3-ea50-465d-ba0e-11f209a640da)
container kuwa-multi-chat-1有成功跑起來，沒有錯誤訊息

**Comment by ifTNT** [comment]
可能要給我完整的log才能判斷，用以下指令就可以取得完整的log
```
cd genai-os/docker
./run.sh logs > compose.log
```

**Comment by yue0211** [comment]
[
[compose.log](https://github.com/kuwaai/genai-os/files/15449571/compose.log)
](url)

此為完整的 log 紀錄

**Comment by ifTNT** [comment]
哈囉，這邊有一篇在 Mac 上安裝 Kuwa 的教學文章，可以參考看看
https://hackmd.io/@cclljj/r1mIc3tNR
