### ISSUE TITLE
Web translation with server error

### ISSUE THREAD

**Issue by x85432** [kuwaai/genai-os#36]
**Describe the bug**
When the model generation done, I was going to translate the result into chinese(zh_tw). Following is the error after I click the tranlation button.

**To Reproduce**
1. After model generation
2. Click the button 
![image](https://github.com/user-attachments/assets/054f405f-aa99-44c6-819c-3639aeddb40b)

**Expected behavior**
Translate **multiple language** including English and Chinese(zh) into Chinese(zh_tw)

**Screenshot**
![image](https://github.com/user-attachments/assets/38c98761-a0c0-4d67-a232-311597d8a212)

**Desktop (please complete the following information):**
 - OS: Windows11 x64
 - Browser: Microsoft Edge
 - Version [v0.3.3]
 - CUDA [Non]
 
**Addition**
Not only happen in our own executor; for instance, system info also occur this issue.

**Comment by x85432** [comment]
@ifTNT 
After coping code from [ChatController.php](https://github.com/kuwaai/genai-os/blob/a2764eb3bed41bcd69ec0c545f1dc44c5f321a6b/src/multi-chat/app/Http/Controllers/ChatController.php) and [ProfileController.php](https://github.com/kuwaai/genai-os/blob/a2764eb3bed41bcd69ec0c545f1dc44c5f321a6b/src/multi-chat/app/Http/Controllers/ProfileController.php) to my own directory, it still show the status code 500 on the page. How should I fix it in a correct way?

**Comment by ifTNT** [comment]
Hey @x85432, 

It sounds like you're running into a caching issue. Try these steps to fix the 500 error:

1. **Manual Patching:** Double-check that you copied the code from `ChatController.php` and `ProfileController.php` correctly. Restart Kuwa after copying the patched files.
2. **Clear Cache:** If the error persists, navigate to the `windows/` directory and run the `build.bat` script. This will rebuild Kuwa and clear any cached files.
3. **Use `update.bat`:** The easiest way to apply patches is with the `update.bat` script. This script will apply the necessary changes and rebuild Kuwa automatically.

Let me know if you're still experiencing problems after trying these steps!
