### ISSUE TITLE
Failed to install genai-os with installation script

### ISSUE THREAD

**Issue by namwoam** [kuwaai/genai-os#52]
**Describe the bug**
Bug during installation process
The installation script kept printing these statements:
```
sh: 124: [: unexpected operator
Passwords do not match. Please enter your password again.
sh: 119: read: Illegal option -s
```

**To Reproduce**
1. Install kuwa on linux machine with the command `curl -fsSL https://raw.githubusercontent.com/kuwaai/genai-os/main/docker/build.sh | sudo`

**Expected behavior**
It should install the kuwa application.

**Screenshots**
![Screenshot from 2024-09-09 13-00-44](https://github.com/user-attachments/assets/a97b8523-a7eb-488f-9628-594c684421f4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - CUDA: 12.4
 - CPU: AMD Ryzen 7 4800HS with Radeon Graphics

**Comment by ifTNT** [comment]
Hi @namwoam,

Could you please test the following command and confirm if it works:

```bash
curl -fsSL https://raw.githubusercontent.com/kuwaai/genai-os/main/docker/build.sh | sudo bash
```

**Comment by namwoam** [comment]
It works, thanks for the help.
