### ISSUE TITLE
TypeError When Calling KUWA API: Expected "usage" as Mapping, Received List

### ISSUE THREAD

**Issue by ryan4559** [kuwaai/genai-os#55]
**Describe the bug**  
在使用 `litellm` 模組呼叫KUWA API時，出現以下 TypeError 錯誤訊息：`TypeError: litellm.types.utils.Usage() argument after ** must be a mapping, not list`，導致無法正確的解析。

**To Reproduce**  
重現此錯誤的步驟：
1. 使用 `litellm` 模組呼叫 API，本次使用crewAI
2. 遇到 TypeError 錯誤
**Expected behavior**  
預期應返回以下格式的 `usage` 資料，而不是list：

```json
"usage": { 
    "queue_time": 0.005218713,
    "prompt_tokens": 50,
    "prompt_time": 0.012402376,
    "completion_tokens": 261,
    "completion_time": 1.047650849,
    "total_tokens": 311,
    "total_time": 1.060053225
}
```
目前輸出的 usage 欄位卻為空列表，顯示如下：
```json
"usage": []
```
**Desktop (please complete the following information):**
 - Version v0.3.4

**Comment by ifTNT** [comment]
The patch [e2185cb](https://github.com/kuwaai/genai-os/commit/e2185cb2ef02b411de1a9c2a828aed0811fc9bd3) should fix this bug.
